apiVersion: v1
kind: Service
metadata:
  name: fodinfo
spec:
  type: ClusterIP
  selector:
    app: fodinfo
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
