version: '3.4'

services:
  podinfo:
    image: podinfo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
