version: '3.4'

services:
  fodinfo:
    image: fodinfo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
