{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fodinfo.fullname" . }}-redis
  labels:
    app: {{ template "fodinfo.fullname" . }}-redis
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "fodinfo.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ template "fodinfo.fullname" . }}-redis
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/redis/config.yaml") . | sha256sum | quote }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ template "fodinfo.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: redis
          image: "{{ .Values.redis.repository }}:{{ .Values.redis.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - redis-server
            - "/redis-master/redis.conf"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 32Mi
          volumeMounts:
            - mountPath: /var/lib/redis
              name: data
            - mountPath: /redis-master
              name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ template "fodinfo.fullname" . }}-redis
            items:
              - key: redis.conf
                path: redis.conf
{{- end }}
