{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fodinfo.serviceAccountName" . }}
  labels:
    {{- include "fodinfo.labels" . | nindent 4 }}
{{- end -}}
